{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thehive.serviceAccountName" . }}
  labels:
{{ include "thehive.labels" . | nindent 4 }}
{{- end -}}
