{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: {{ .Values.ingress.hostname }} 
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }} 
          servicePort: {{ .Values.service.port }}
        pathType: Prefix  
{{- end -}}
