apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cortex
  name: cortex
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cortex
    spec:
      containers:
      - image: thehiveproject/cortex:latest
        name: cortex
        ports:
        - containerPort: 9001
          hostIP: 0.0.0.0
        resources: {}
      restartPolicy: Always
status: {}
