apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: thehive
  name: thehive
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: thehive
    spec:
      containers:
      - args:
        - --cortex-port
        - "9001"
        image: thehiveproject/thehive:latest
        name: thehive
        ports:
        - containerPort: 9000
          hostIP: 0.0.0.0
        resources: {}
      restartPolicy: Always
status: {}
